name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_widget_from_html: ^0.9.0
  fluttertoast: ^8.2.8
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/images/logo_loki.png
  - assets/images/foto_welcome.jpg
  - assets/images/foto_start.jpg
  - assets/images/foto_opciones.jpg

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 600
        - asset: assets/fonts/Jost-Extralight.ttf
          weight: 200
        - asset: assets/fonts/Jost-Black.ttf
          weight: 800